source "http://rubygems.org"

gem "aws-sdk", "~> 1.8.0"
gem "sinatra", "~> 1.3.3"
gem "sinatra-reloader", "~> 1.0"
gem "thin", "~> 1.5.0"
gem "haml"
gem "sinatra-contrib"
gem "template-inheritance", "~> 0.3"
gem "rack_csrf", "~> 2.4.0"
gem  "uglifier"
gem "sinatra-activerecord"
gem "dbi", "~> 0.4.5"
# gem "mysql", "~> 2.9.0"
gem "rake"
